# website base url
baseURL = 'https://hugo.njxzc.top/'
# website language
languageCode = 'en-us'
# website title
title = 'Hugo Simple Theme'
# hugo theme
theme = 'Hugo-Theme-Simple'
# pageinate
paginate = 5

# website menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Archive"
    url = "/archive/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

# website params
[params]
  footer= "&copy; 2022-{Year} Made with ❤️ By Jiakai"
  baidutongji = ""
  googleanalytics = ""

# website permanent link
[permalinks]
  blog = "/:year/:month/:slug"

# website markdown render
[markup]
  # goldmark is the default markdown render of hugo
  [markup.goldmark]
    # more explainations, pls visit: https://gohugo.io/getting-started/configuration-markup/#goldmark
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 3
        ordered = false
     