# website base url
baseURL = 'https://hugo.njxzc.top/'
# website language
languageCode = 'en-us'
# website title
title = 'Hugo Simple Theme'
# hugo theme
theme = 'hugo-simple-theme'
# generate url without slash
uglyURLs = true

# website menu
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

# website permanent link
[permalinks]
  blog = "/:year/:month/:slug"

# website markdown render
[markup]
  # goldmark is the default markdown render of hugo
  [markup.goldmark]
    # extensions
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
    [markup.tableOfContents]
        startLevel = 1
        endLevel = 2
        ordered = false
     